from flask import Flask, render_template, request, jsonify, Response
from datetime import date, timedelta, datetime
import os
import psycopg
from psycopg.rows import dict_row
app=Flask(__name__); DB_URL=os.environ.get('DATABASE_URL')
DEFAULT_STAFF=['LÂN','SƯƠNG','Thoa','MINH ANH','HƯNG','THẢO','THƯ','Xuân','Nhi','Hiền','Ngân','HIỀN Mới','Trang']
def db():
 if not DB_URL: raise RuntimeError('DATABASE_URL is not set')
 return psycopg.connect(DB_URL, row_factory=dict_row)
def init():
 c=db()
 c.execute("""CREATE TABLE IF NOT EXISTS staff(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,active INTEGER DEFAULT 1,staff_type TEXT DEFAULT 'baito',pay_type TEXT DEFAULT 'hourly',hourly_rate INTEGER DEFAULT 1250,monthly_salary INTEGER DEFAULT 0,sort_order INTEGER DEFAULT 0)""")
 c.execute("""CREATE TABLE IF NOT EXISTS shifts(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,staff_id INTEGER,work_date TEXT,start TEXT,"end" TEXT,break_min INTEGER DEFAULT 0,break_start TEXT,break_end TEXT,UNIQUE(staff_id,work_date))""")
 c.execute("""CREATE TABLE IF NOT EXISTS kibo_submissions(staff_id INTEGER NOT NULL,week_start TEXT NOT NULL,submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(staff_id,week_start))""")
 for col,sql in [('staff_type',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS staff_type TEXT DEFAULT 'baito'"),('pay_type',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS pay_type TEXT DEFAULT 'hourly'"),('hourly_rate',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS hourly_rate INTEGER DEFAULT 1250"),('monthly_salary',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS monthly_salary INTEGER DEFAULT 0"),('sort_order',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0"),('email',"ALTER TABLE staff ADD COLUMN IF NOT EXISTS email TEXT")]:
  c.execute(sql)
 c.execute("ALTER TABLE shifts ADD COLUMN IF NOT EXISTS break_start TEXT")
 c.execute("ALTER TABLE shifts ADD COLUMN IF NOT EXISTS break_end TEXT")
 c.execute("ALTER TABLE shifts ADD COLUMN IF NOT EXISTS is_kibo INTEGER DEFAULT 0")
 if c.execute('select count(*) n from staff').fetchone()['n']==0:
  c.cursor().executemany('insert into staff(name) values(%s)', [(x,) for x in DEFAULT_STAFF])
 rows=c.execute('select id,sort_order from staff order by id').fetchall()
 if rows and all((r['sort_order'] or 0)==0 for r in rows):
  for i,r in enumerate(rows): c.execute('update staff set sort_order=%s where id=%s',(i,r['id']))
 c.commit();c.close()
def monday(s=None):
 d=datetime.strptime(s,'%Y-%m-%d').date() if s else date.today();return d-timedelta(days=d.weekday())
def hdiff(a,b):
 if not a or not b:return 0
 x=datetime.strptime(a,'%H:%M');y=datetime.strptime(b,'%H:%M');return max(0,(y-x).seconds/3600)
def hours(r):
 if not r:return 0
 br=hdiff(r['break_start'],r['break_end']) if r['break_start'] and r['break_end'] else 0
 return max(0,hdiff(r['start'],r['end'])-br)
@app.route('/')
def index():
 m=monday(request.args.get('week'));days=[m+timedelta(days=i) for i in range(7)];c=db();staff=c.execute('select * from staff where active=1 order by sort_order,id').fetchall();rows=c.execute('select * from shifts where work_date between %s and %s',(str(days[0]),str(days[-1]))).fetchall();# Monthly totals for the month containing the week start.
 month_start=m.replace(day=1)
 if m.month==12: month_end=date(m.year+1,1,1)-timedelta(days=1)
 else: month_end=date(m.year,m.month+1,1)-timedelta(days=1)
 month_rows=c.execute('select * from shifts where work_date between %s and %s',(str(month_start),str(month_end))).fetchall()
 kibo_rows=c.execute('select staff_id,submitted_at from kibo_submissions where week_start=%s',(str(m),)).fetchall()
 # Backward compatibility: 希望 already submitted before submission tracking was added.
 legacy_kibo=c.execute('select distinct staff_id from shifts where work_date between %s and %s and is_kibo=1',(str(days[0]),str(days[-1]))).fetchall()
 c.close();kibo_status={r['staff_id']:r['submitted_at'] for r in kibo_rows}
 for r in legacy_kibo:kibo_status.setdefault(r['staff_id'],None)
 sm={(r['staff_id'],r['work_date']):r for r in rows}
 totals={s['id']:sum(hours(sm.get((s['id'],str(d)))) for d in days) for s in staff}
 monthly_totals={s['id']:sum(hours(r) for r in month_rows if r['staff_id']==s['id']) for s in staff}
 pay={s['id']:(round(monthly_totals[s['id']]*(s['hourly_rate'] or 0)) if s['pay_type']=='hourly' else (s['monthly_salary'] or 0)) for s in staff}
 baito_monthly_pay=sum(round(monthly_totals[s['id']]*(s['hourly_rate'] or 0)) for s in staff if s['staff_type']=='baito')
 daily_totals={str(d):sum(hours(sm.get((s['id'],str(d)))) for s in staff) for d in days}
 monthly_all_hours=sum(monthly_totals.values())
 return render_template('index.html',staff=staff,days=days,sm=sm,totals=totals,monthly_totals=monthly_totals,pay=pay,baito_monthly_pay=baito_monthly_pay,daily_totals=daily_totals,monthly_all_hours=monthly_all_hours,kibo_status=kibo_status,prev=m-timedelta(days=7),nxt=m+timedelta(days=7),current_month=m.month,current_year=m.year)
@app.get('/month')
def month_view():
 try:
  y=int(request.args.get('year') or date.today().year); mo=int(request.args.get('month') or date.today().month)
  first=date(y,mo,1)
 except Exception: first=date.today().replace(day=1); y=first.year; mo=first.month
 next_first=date(y+1,1,1) if mo==12 else date(y,mo+1,1)
 last=next_first-timedelta(days=1); days=[first+timedelta(days=i) for i in range((last-first).days+1)]
 prev=(first-timedelta(days=1)).replace(day=1); nxt=next_first
 c=db(); staff=c.execute('select * from staff where active=1 order by sort_order,id').fetchall(); rows=c.execute('select * from shifts where work_date between %s and %s',(str(first),str(last))).fetchall(); c.close()
 sm={(r['staff_id'],r['work_date']):r for r in rows}; totals={s['id']:sum(hours(sm.get((s['id'],str(d)))) for d in days) for s in staff}
 return render_template('month.html',staff=staff,days=days,sm=sm,totals=totals,year=y,month=mo,prev_year=prev.year,prev_month=prev.month,next_year=nxt.year,next_month=nxt.month)

@app.post('/shift')
def shift():
 x=request.get_json();c=db()
 if not x.get('start') or not x.get('end'):c.execute('delete from shifts where staff_id=%s and work_date=%s',(x['staff_id'],x['date']))
 else:c.execute('''insert into shifts(staff_id,work_date,start,"end",break_start,break_end,break_min,is_kibo) values(%s,%s,%s,%s,%s,%s,0,0) on conflict(staff_id,work_date) do update set start=excluded.start,"end"=excluded."end",break_start=excluded.break_start,break_end=excluded.break_end,is_kibo=0''',(x['staff_id'],x['date'],x['start'],x['end'],x.get('break_start') or None,x.get('break_end') or None))
 c.commit();c.close();return jsonify(ok=True)

@app.route('/kibo',methods=['GET','POST'])
def kibo():
 c=db();staff=c.execute('select id,name from staff where active=1 order by sort_order,id').fetchall()
 message=None; error=None; submitted=0; locked=0
 raw_week=request.values.get('week')
 try:m=monday(raw_week) if raw_week else monday()+timedelta(days=7)
 except Exception:m=monday()+timedelta(days=7)
 days=[m+timedelta(days=i) for i in range(7)]
 try:selected_id=int(request.values.get('staff_id') or (staff[0]['id'] if staff else 0))
 except Exception:selected_id=0
 valid_ids={s['id'] for s in staff}
 if selected_id not in valid_ids:selected_id=staff[0]['id'] if staff else 0
 if request.method=='POST':
  entries=[]
  for i,d in enumerate(days):
   start=(request.form.get(f'start_{i}') or '').strip();end=(request.form.get(f'end_{i}') or '').strip()
   if bool(start)!=bool(end):error=f'{d.strftime("%d/%m")}: cần nhập đủ giờ bắt đầu và kết thúc';break
   if start and end:
    try:
     a=datetime.strptime(start,'%H:%M');b=datetime.strptime(end,'%H:%M')
     if b<=a:raise ValueError()
    except Exception:error=f'{d.strftime("%d/%m")}: giờ kết thúc phải sau giờ bắt đầu';break
   entries.append((str(d),start,end))
  if not error and selected_id:
   try:
    for work_date,start,end in entries:
     existing=c.execute('select is_kibo from shifts where staff_id=%s and work_date=%s',(selected_id,work_date)).fetchone()
     if existing and not existing['is_kibo']:
      locked+=1;continue
     if start and end:
      c.execute('''insert into shifts(staff_id,work_date,start,"end",break_min,break_start,break_end,is_kibo) values(%s,%s,%s,%s,0,NULL,NULL,1) on conflict(staff_id,work_date) do update set start=excluded.start,"end"=excluded."end",break_start=NULL,break_end=NULL,is_kibo=1''',(selected_id,work_date,start,end));submitted+=1
     else:c.execute('delete from shifts where staff_id=%s and work_date=%s and is_kibo=1',(selected_id,work_date))
    c.execute('''insert into kibo_submissions(staff_id,week_start,submitted_at) values(%s,%s,CURRENT_TIMESTAMP) on conflict(staff_id,week_start) do update set submitted_at=CURRENT_TIMESTAMP''',(selected_id,str(days[0])))
    c.commit();message=f'Đã gửi {submitted} ca 希望 cho tuần {days[0].strftime("%d/%m")}–{days[-1].strftime("%d/%m/%Y")}.'
    if locked:message+=f' Có {locked} ngày quản lý đã chốt nên không bị ghi đè.'
   except Exception:
    c.rollback();error='Không lưu được 希望シフト. Vui lòng thử lại.'
 rows=c.execute('select work_date,start,"end",is_kibo from shifts where staff_id=%s and work_date between %s and %s',(selected_id,str(days[0]),str(days[-1]))).fetchall() if selected_id else []
 c.close();existing={r['work_date']:r for r in rows}
 return render_template('kibo.html',staff=staff,selected_id=selected_id,days=days,existing=existing,message=message,error=error)
@app.post('/staff')
def staff_action():
 x=request.get_json();c=db();a=x.get('action')
 if a=='add' and x.get('name','').strip():
  mx=c.execute('select coalesce(max(sort_order),-1)+1 n from staff').fetchone()['n'];sid=c.execute('insert into staff(name,sort_order) values(%s,%s) returning id',(x['name'].strip(),mx)).fetchone()['id']
 elif a=='rename' and x.get('name','').strip(): c.execute('update staff set name=%s where id=%s',(x['name'].strip(),x['id']));sid=x['id']
 elif a=='delete': c.execute('update staff set active=0 where id=%s',(x['id'],));sid=x['id']
 elif a=='email':
  c.execute('update staff set email=%s where id=%s',((x.get('email') or '').strip() or None,x['id']));sid=x['id']
 elif a=='update':
  c.execute('update staff set staff_type=%s,pay_type=%s,hourly_rate=%s,monthly_salary=%s,email=%s where id=%s',(x.get('staff_type','baito'),x.get('pay_type','hourly'),int(x.get('hourly_rate') or 0),int(x.get('monthly_salary') or 0),(x.get('email') or '').strip() or None,x['id']));sid=x['id']
 else:c.close();return jsonify(ok=False),400
 c.commit();c.close();return jsonify(ok=True,id=sid)


@app.post('/move-week')
def move_week():
 x=request.get_json() or {}
 try:
  src=monday(x.get('source_week'))
  raw=x.get('target_date')
  if not raw: return jsonify(ok=False,error='missing target date'),400
  target=monday(raw)
 except Exception:
  return jsonify(ok=False,error='invalid date'),400
 if src==target: return jsonify(ok=True,target=str(target),moved=0)
 c=db()
 src_end=src+timedelta(days=6); target_end=target+timedelta(days=6)
 source_rows=c.execute('select * from shifts where work_date between %s and %s',(str(src),str(src_end))).fetchall()
 conflicts=c.execute('select count(*) n from shifts where work_date between %s and %s',(str(target),str(target_end))).fetchone()['n']
 if conflicts and not x.get('force'):
  c.close(); return jsonify(ok=False,conflict=True,count=conflicts,target=str(target)),409
 try:
  c.execute('begin')
  if conflicts: c.execute('delete from shifts where work_date between %s and %s',(str(target),str(target_end)))
  # Move through temporary dates first so UNIQUE(staff_id,work_date) can never collide.
  temp_base=date(2099,1,4)
  moved=[]
  for i,r in enumerate(source_rows):
   old=datetime.strptime(r['work_date'],'%Y-%m-%d').date(); offset=(old-src).days
   tmp=temp_base+timedelta(days=offset)
   c.execute('update shifts set work_date=%s where id=%s',(str(tmp),r['id']))
   moved.append((r['id'],str(target+timedelta(days=offset))))
  for rid,newdate in moved: c.execute('update shifts set work_date=%s where id=%s',(newdate,rid))
  c.commit()
 except Exception as e:
  c.rollback(); c.close(); return jsonify(ok=False,error=str(e)),500
 c.close(); return jsonify(ok=True,target=str(target),moved=len(source_rows))

@app.get('/backup.csv')
def backup_csv():
 import csv, io
 c=db()
 staff=c.execute('select id,name,active,staff_type,pay_type,hourly_rate,monthly_salary,sort_order from staff order by sort_order,id').fetchall()
 shifts=c.execute('select id,staff_id,work_date,start,"end",break_start,break_end,break_min from shifts order by work_date,staff_id').fetchall()
 c.close()
 out=io.StringIO(); w=csv.writer(out)
 w.writerow(['type','id','staff_id/name','work_date/active','start/staff_type','end/pay_type','break_start/hourly_rate','break_end/monthly_salary','break_min/sort_order'])
 for s in staff: w.writerow(['staff',s['id'],s['name'],s['active'],s['staff_type'],s['pay_type'],s['hourly_rate'],s['monthly_salary'],s['sort_order']])
 for r in shifts: w.writerow(['shift',r['id'],r['staff_id'],r['work_date'],r['start'],r['end'],r['break_start'] or '',r['break_end'] or '',r['break_min'] or 0])
 filename='shift-backup-'+datetime.now().strftime('%Y%m%d-%H%M')+'.csv'
 return Response(out.getvalue(),mimetype='text/csv; charset=utf-8',headers={'Content-Disposition':'attachment; filename='+filename})

@app.post('/restore-backup')
def restore_backup():
 import csv, io
 f=request.files.get('backup')
 if not f: return jsonify(ok=False,error='Chưa chọn file backup'),400
 try:
  text=f.read().decode('utf-8-sig'); rows=list(csv.reader(io.StringIO(text)))
  if not rows or rows[0][:2]!=['type','id']: raise ValueError('File backup không hợp lệ')
  staff_rows=[r for r in rows[1:] if r and r[0]=='staff']; shift_rows=[r for r in rows[1:] if r and r[0]=='shift']
  c=db(); idmap={}
  try:
   c.execute('begin')
   for r in staff_rows:
    oldid=int(r[1]); name=r[2]; active=int(r[3] or 1); stype=r[4] or 'baito'; ptype=r[5] or 'hourly'; hourly=int(r[6] or 0); monthly=int(r[7] or 0); order=int(r[8] or 0)
    found=c.execute('select id from staff where name=%s order by active desc,id limit 1',(name,)).fetchone()
    if found: nid=found['id']; c.execute('update staff set active=%s,staff_type=%s,pay_type=%s,hourly_rate=%s,monthly_salary=%s,sort_order=%s where id=%s',(active,stype,ptype,hourly,monthly,order,nid))
    else: nid=c.execute('insert into staff(name,active,staff_type,pay_type,hourly_rate,monthly_salary,sort_order) values(%s,%s,%s,%s,%s,%s,%s) returning id',(name,active,stype,ptype,hourly,monthly,order)).fetchone()['id']
    idmap[oldid]=nid
   for r in shift_rows:
    nid=idmap.get(int(r[2]));
    if not nid: continue
    c.execute('''insert into shifts(staff_id,work_date,start,"end",break_start,break_end,break_min) values(%s,%s,%s,%s,%s,%s,%s) on conflict(staff_id,work_date) do update set start=excluded.start,"end"=excluded."end",break_start=excluded.break_start,break_end=excluded.break_end,break_min=excluded.break_min''',(nid,r[3],r[4],r[5],r[6] or None,r[7] or None,int(r[8] or 0)))
   c.commit()
  except Exception:
   c.rollback(); raise
  finally: c.close()
  return jsonify(ok=True,staff=len(staff_rows),shifts=len(shift_rows))
 except Exception as e: return jsonify(ok=False,error=str(e)),400

@app.post('/staff/reorder')
def staff_reorder():
 x=request.get_json() or {}; order=x.get('order') or []
 c=db()
 for i,sid in enumerate(order): c.execute('update staff set sort_order=%s where id=%s',(i,int(sid)))
 c.commit();c.close();return jsonify(ok=True)

init()
if __name__=='__main__':app.run(host='0.0.0.0',port=int(os.environ.get('PORT',8082)),debug=False)
